variables:
  CICD_PROJECT_FILE: DeploymentDemo.xcodeproj
  CICD_DEFAULT_SCHEME: DeploymentDemo
  CICD_DEFAULT_CONFIGURATION: Debug
  CICD_TEST_DESTINATION: platform=iOS Simulator,name=iPhone 16

fastlane:
  FASTLANE_TEAM_ID: ""
  FASTLANE_ITC_TEAM_ID: ""
  FASTLANE_BUNDLE_IDENTIFIER: com.capgemini.DeploymentDemo

match:
  MATCH_GIT_URL: git@github.com:your-org/certificates.git

notification:
  provider: teams
  webhook_env: TEAM_WEBHOOK_URL
